.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. Altmarkets_qt test_Altmarkets_qt
clean: FORCE
	$(MAKE) -C .. Altmarkets_qt_clean test_Altmarkets_qt_clean
check: FORCE
	$(MAKE) -C .. test_Altmarkets_qt_check
Altmarkets-qt Altmarkets-qt.exe: FORCE
	 $(MAKE) -C .. Altmarkets_qt
