#!/bin/bash

# This is a thin wrapper around Altmarkets-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using Altmarkets-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_Altmarketsd

# Grab the value of $REAL_AltmarketsCLI which may be Altmarkets-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_AltmarketsCLI}" "$@" | sed 's/\r//'
